version: '3'
services:
  n8n:
    image: registry.megavn.net/n8nio/n8n:dev
    build: .
    ports:
      - '5678:5678'
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - default

volumes:
  n8n_data:
