version: '3'
services:
  n8n:
    image: registry.megavn.net/n8nio/n8n:1.74.0
    build:
      context: .
      dockerfile: docker/images/n8n-custom/Dockerfile.my
    ports:
      - '5678:5678'
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - default
    depends_on:
      - db
  db:
    image: postgres:13.13
    ports:
      - '5432:5432'
    env_file:
      - .env
    environment:
      TZ: Asia/Ho_Chi_Minh
      POSTGRES_DB: "${DB_POSTGRESDB_DATABASE}"
      POSTGRES_USER: "${DB_POSTGRESDB_USER}"
      POSTGRES_PASSWORD: "${DB_POSTGRESDB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: "redis:6.2-alpine"
    restart: always
    volumes:
      - "redis_data:/data"
volumes:
  n8n_data:
  postgres_data:
  redis_data:


